### ISSUE TITLE
Problems connecting VSCode and Jupyter server

### ISSUE THREAD

**Issue by dklotz** [jakoch/jupyter-devbox#6]
First of all: thanks for all the effort, this looks like a great starting place for an AI/ML/Python devcontainer setup! 

Sorry for using issues as a "support channel" - if that's not something you want to do, feel free to just close the issue!

I wanted to try this (on my M1 Macbook, so all this relates to the newly added arm64 support from #5) and I ran into the problem that when I opened/started the devcontainer, the jupyter server wasn't running (probably related to #1 - although I see that line has already been added to `devcontainer.json`). After manually starting `start-notebook.sh`, jupyter runs and I can connect to the web interface without problems. But when I open `notebooks/test.ipynb` inside of VSCode, it doesn't find any existing Jupyter kernels. I tried both offered options ("Python Environments" and "Existing Jupyter Server"), but haven't been succesfull with either: 
- The first fails and tells me to pip install `ipykernel`- which should already be there according to the Dockerfile. 
- For the second I tried `http://localhost:8888/` and `http://localhost:8888/tree` (and the same with `127.0.0.1` instead of localhost), but it fails to connect without any error message. I can see the following 404s in the log of `start-notebook.sh` each time I try to connect the extension to the server, so maybe I just need to use a different URL? 
<img width="905" alt="image" src="https://github.com/jakoch/jupyter-devbox/assets/2143593/65a4ee88-2f08-47a3-a8c2-f2d8aaecc4c0">

**Comment by jakoch** [comment]
Referencing upstream issue: https://github.com/microsoft/vscode-jupyter/issues/15163

**Comment by leviznull** [comment]
@dklotz I had the same issue running on amd64 and managed to fix it by adding the following to the devcontainer

```
"customizations": {
	"vscode": {
		"extensions": [
			// force jupyter to default to our kernel on all notebooks
			"donjayamanne.vscode-default-python-kernel"
		],
		"settings": {
                        // configure our venv to work with vscode automatically
			"python.terminal.activateEnvironment": true,
			"python.defaultInterpreterPath": "$/opt/venv/bin/python3.11"
		}
	}
}
```

@jakoch In my opinion it would be worthwhile merging this change, unless you see any complications arising from it.

**Comment by dklotz** [comment]
Thanks, the workaround be @leviznull worked for me! I had to fix one typo (there's a `$` sign in the defaultInterpreterPath that doesn't belong there), but after that the notebook worked fine in the extension without any additional setup (apart from once having to select the venv as the kernel, so somehow the vscode-default-python-kernel didn't really do its job, but everything still works after that step).

**Comment by jakoch** [comment]
nice workaround @leviznull  
you can find the new images here:
https://github.com/jakoch/jupyter-devbox/pkgs/container/jupyter-devbox/178943636?tag=sha-509ce88
